title: Emile Klotz # your name (or website title) here
logo: "/images/logo..jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  PHD Graduate Student in optics and machine learning
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/emile-klotz-78a936152/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
